---
title: Action Plumbing, Heating & Cooling Services, LLC
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: false
  testimonials:
    title: Testimonials
    output: false
  uploads:
    title: Uploads
    output: true
baseurl: 
url: 
phone: 607-205-1177
exclude:
- Gemfile
- Gemfile.lock
markdown: kramdown
gems:
- jekyll-feed
- jekyll-coffeescript
